### PR TITLE
Testing out a multipage build

### PR DESCRIPTION
**Pull request by bryanjswift**
After discussion in #43 this was a branch to see how far I a route based implementation could get.

Refs bryanjswift/mogwai#1

### CODE REVIEW

**Comment by bryanjswift** [comment]
@schell I took out the commit where I commented out things in `dom.rs` since you made changes there.

**Comment by schell** [comment]
Let me know when you are done pushing commits and I'll review and merge :)

**Comment by bryanjswift** [comment]
> Let me know when you are done pushing commits and I'll review and merge :)

@schell I'm through, I'm planning to keep tinkering with this example but I'll do so in a new branch

**Comment by bryanjswift** [comment]
I was mentally stuck on `View` being the "correct" result of the routes but there's no reason that is true especially if `ViewBuilder` enables SSR then each route realistically should result in a `ViewBuilder` because (in theory) each route should be renderable server side. Anyway I (once again) think I'm done making edits to this branch!

**Comment by bryanjswift** [comment]
@schell I was going to rebase this branch to keep it up-to-date with the base branch. Let me know if you'd prefer I leave it as is.

**Comment by schell** [comment]
Rebasing is good with me :+1:

**Pull request merged**
